---
blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/wojciech-kulik/xcodebuild.nvim/discussions/categories/q-a
    about: Please use GitHub discussions for questions.
