---
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/MethodLength:
  Max: 30
Style/IfUnlessModifier:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Style/OptionalBooleanParameter:
  Enabled: false
