name: Quality Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install luacheck
      - name: Lint
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          make lint

  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install stylua
      - name: Check
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          make format-check

  lsp-check:
    name: LSP Error Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install lua-language-server
      - name: Check
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          make lsp-check

  help-check:
    name: Help Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo modules
        uses: actions/cache@v4
        id: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-
      - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        name: Install
        run: cargo install lemmy-help --features=cli
      - name: Check
        run: make help-check
